# app/services/asterisk_trunk_generator.py

from __future__ import annotations

import os
import re
import subprocess
from datetime import datetime

from app.config import settings


GENERATED_FILE = settings.TRUNK_CONFIG_FILE
APPLY_SCRIPT = settings.TRUNK_APPLY_SCRIPT


def _text(value, default=""):
    if value is None:
        return default

    if hasattr(value, "value"):
        return str(value.value)

    return str(value)


def _safe_endpoint(value: str) -> str:
    value = _text(value).strip()
    value = re.sub(r"[^A-Za-z0-9_]", "_", value)
    value = re.sub(r"_+", "_", value)
    value = value.strip("_")

    if not value:
        value = "voicecrm_trunk"

    return value[:80]


def _server_with_port(host: str) -> str:
    host = _text(host).strip()

    if not host:
        return ""

    if ":" in host:
        return host

    return f"{host}:5060"


def _bool_value(value, default=True) -> bool:
    if value is None:
        return default

    if isinstance(value, bool):
        return value

    return str(value).lower().strip() in ["1", "true", "yes", "y", "on"]


def generate_pjsip_config(trunks) -> dict:
    lines = []

    lines.append("; =====================================================")
    lines.append("; AUTO-GENERATED BY VOICECRM")
    lines.append("; Do not edit manually.")
    lines.append(f"; Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("; =====================================================")
    lines.append("")

    generated_count = 0
    skipped = []

    for trunk in trunks:
        is_active = _bool_value(getattr(trunk, "is_active", True), True)

        if not is_active:
            continue

        managed_by_crm = _bool_value(getattr(trunk, "managed_by_crm", True), True)

        # Existing/manual Asterisk trunks like mobinet_75004814 must NOT be generated again.
        if not managed_by_crm:
            skipped.append({
                "id": getattr(trunk, "id", None),
                "number": _text(getattr(trunk, "number", "")),
                "endpoint": _text(getattr(trunk, "asterisk_endpoint", "")),
                "reason": "managed_by_crm=false, existing Asterisk trunk skipped",
            })
            continue

        number = _text(getattr(trunk, "number", "")).strip()
        sip_host = _text(getattr(trunk, "sip_host", "")).strip()
        sip_username = _text(getattr(trunk, "sip_username", "")).strip()
        sip_password = _text(getattr(trunk, "sip_password", "")).strip()

        endpoint = _safe_endpoint(
            getattr(trunk, "asterisk_endpoint", None)
            or f"trunk_{number}"
        )

        if not number or not sip_host or not sip_username or not sip_password:
            skipped.append({
                "id": getattr(trunk, "id", None),
                "number": number,
                "endpoint": endpoint,
                "reason": "missing number/sip_host/sip_username/sip_password",
            })
            continue

        server = _server_with_port(sip_host)

        sip_domain = _text(getattr(trunk, "sip_domain", None), sip_host).strip()
        transport = _text(getattr(trunk, "transport", None), "transport-udp").strip()

        # CRM-added SIP trunks are outbound-only.
        inbound_context = "voicecrm-deny-inbound"

        lines.append("; ------------------------------")
        lines.append(f"; SIP trunk: {number}")
        lines.append(f"; Endpoint: {endpoint}")
        lines.append("; ------------------------------")
        lines.append("")

        lines.append(f"[{endpoint}]")
        lines.append("type=endpoint")
        lines.append("rtp_timeout=3")
        lines.append("rtp_timeout_hold=3")
        lines.append("direct_media=no")
        lines.append(f"transport={transport}")
        lines.append(f"context={inbound_context}")
        lines.append("disallow=all")
        lines.append("allow=ulaw,alaw")
        lines.append(f"outbound_auth={endpoint}_auth")
        lines.append(f"aors={endpoint}_aor")
        lines.append(f"from_user={number}")
        lines.append(f"from_domain={sip_domain}")
        lines.append("rewrite_contact=yes")
        lines.append("rtp_symmetric=yes")
        lines.append("force_rport=yes")
        lines.append("")

        lines.append(f"[{endpoint}_auth]")
        lines.append("type=auth")
        lines.append("auth_type=userpass")
        lines.append(f"username={sip_username}")
        lines.append(f"password={sip_password}")
        lines.append(f"realm={sip_domain}")
        lines.append("")

        lines.append(f"[{endpoint}_aor]")
        lines.append("type=aor")
        lines.append(f"contact=sip:{server}")
        lines.append("qualify_frequency=30")
        lines.append("max_contacts=10")
        lines.append("")

        # No type=identify section on purpose.
        #
        # These trunks are outbound-only and authenticate by registration, so an
        # IP match adds nothing. It also actively breaks the common case of two
        # numbers from the same provider: both would emit the same
        # "match=<provider ip>" pointing at different endpoints, which Asterisk
        # cannot resolve. The hand-written mobinet trunks omit identify for the
        # same reason.

        lines.append(f"[{endpoint}_reg]")
        lines.append("type=registration")
        lines.append(f"transport={transport}")
        lines.append(f"outbound_auth={endpoint}_auth")
        lines.append(f"server_uri=sip:{server}")
        lines.append(f"client_uri=sip:{sip_username}@{sip_domain}")
        lines.append(f"contact_user={sip_username}")
        lines.append("retry_interval=60")
        lines.append("forbidden_retry_interval=60")
        lines.append("auth_rejection_permanent=false")
        lines.append("expiration=3600")
        lines.append("")
        lines.append("")

        generated_count += 1

    if generated_count == 0:
        lines.append("; No active CRM-managed SIP trunks.")
        lines.append("; Existing/manual trunks such as mobinet are not generated here.")
        lines.append("")

    os.makedirs(os.path.dirname(GENERATED_FILE), exist_ok=True)

    with open(GENERATED_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return {
        "ok": True,
        "generated_file": GENERATED_FILE,
        "generated_count": generated_count,
        "skipped": skipped,
    }


def apply_pjsip_config() -> dict:
    try:
        result = subprocess.run(
            ["sudo", "-n", APPLY_SCRIPT],
            capture_output=True,
            text=True,
            timeout=20,
        )

        return {
            "ok": result.returncode == 0,
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr,
        }

    except Exception as exc:
        return {
            "ok": False,
            "returncode": -1,
            "stdout": "",
            "stderr": str(exc),
        }